[tools]
gitleaks = "8.30.1"
ruff = "0.15.8"
ty = "0.0.26"
uv = "0.11.2"

[tasks.lint]
run = "ruff check"

[tasks.typecheck]
run = "ty check"

[tasks.test]
depends = ["lint", "typecheck"]
run = "uv run pytest"

[tasks.build]
depends = ["lint", "typecheck", "test"]
run = "uv build"

[tasks.generate-docs]
depends = ["lint", "typecheck", "test"]
run = "uv run typer budy utils docs --output README.md --name budy"

[tasks.ci]
depends = [
  "lint",
  "typecheck",
  "test",
  "build",
  "generate-docs",
]

[tasks.gitleaks]
description = "Scan the repository for secrets"
run = "gitleaks dir ."

[tasks.pre-commit]
description = "Run pre-commit checks"
depends = ["gitleaks"]
